import Head from "next/head";
import { ReactNode, useEffect } from "react";
import styles from '@/styles/Home.module.css'
import Image from 'next/image'
import firebase from '../lib/firebase';
import router from 'next/router';

export default function Layout({ children }: { children: ReactNode }) {
    
    useEffect(() => {
        const unsubscribe = firebase.authData.onAuthStateChanged(async (authState) => {
            console.log(router.route)
            if (!authState && !router.route.includes('login')) {
                router.push('/login')
            }

            if (authState && router.route.includes('login')) {
                router.push('/')
            }
        })
        return () => unsubscribe();
    },[])

    return (<div className={styles.container}>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <meta name="viewport" content="initial-scale=1, width=device-width" />
        </Head>
        {children}
    </div>)
}