import Head from "next/head";
import { ReactNode, useEffect } from "react";
import styles from '@/styles/Home.module.css'
import Image from 'next/image'
import firebase from '../lib/firebase';
import router from 'next/router';

export default function Layout({ children }: { children: ReactNode }) {
    
    useEffect(() => {
        console.log(firebase.authData.app)
        if (!firebase.getAuth().currentUser) {
            router.push('/login')
        }
    },[])

    return (<div className={styles.container}>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <meta name="viewport" content="initial-scale=1, width=device-width" />
        </Head>
        {children}
    </div>)
}